[build]
  command = "npm run build:netlify"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["ejs", "openid-client"]
  included_files = ["src/views/**"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server"
  status = 200

[[redirects]]
  from = "/auth/*"
  to = "/.netlify/functions/server"
  status = 200

[[redirects]]
  from = "/apply/*"
  to = "/.netlify/functions/server"
  status = 200

[[redirects]]
  from = "/public/*"
  to = "/public/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

